name: aba
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  expandable: ^4.1.4
  fast_qr_reader_view: ^0.1.5
  flutter_icons: ^1.1.0
  flutter_qr_reader: ^1.0.5
  get: ^3.25.6
  get_state_manager: ^3.13.0
  percent_indicator: ^2.1.9+1
  qrcode: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    - assets/suth.jpg
    - assets/transfer.png
    - assets/usd.png
    - assets/vs-card.png
    - assets/qr-payment.png
    - assets/phone.png
    - assets/marker.png
    - assets/deposit.png
    - assets/atm.png
    - assets/account.png
    - assets/market2.webp
    - assets/transfer2.png
    - assets/cellcard2.jpg
    - assets/Dollar symbol inside circle free icon 4.png
    - assets/cash-in-logo.png
    - assets/vector-logo.png
    - assets/sabay.jpg
    - assets/schedule.png
    - assets/Inbox-Empty-icon.png
    - assets/ABA_Visa_Credit.png
    - assets/Debit_card.png
    - assets/Master_card.png
    - assets/logo-visa.png
    - assets/star.png
    - assets/safe-deposit.png
    - assets/abaloans.png
    #   - images/a_dot_burr.jpeg
    #   - images/a_dot_ham.jpeg
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.
    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
